-- ============================================================
-- Alpha Bot — Supabase Database Setup v2 (Cloud Bot)
-- Run this in Supabase SQL Editor.
-- If you ran v1 before, this adds the new tables only.
-- ============================================================

create extension if not exists "uuid-ossp";

-- ── bot_status (replaces bot_state) ───────────────────────
-- Single row per user. Updated by the backend worker every 30s.
create table if not exists bot_status (
  id                uuid primary key default uuid_generate_v4(),
  user_id           uuid not null references auth.users(id) on delete cascade,
  status            text not null default 'STOPPED',  -- RUNNING | PAUSED | STOPPED
  server_online     boolean default false,
  last_analysis_time bigint,       -- Unix ms
  last_candle_time   bigint,       -- Unix ms
  error_status      text,
  current_signal    jsonb,         -- { action, direction, strategy, confidence, regime }
  current_regime    text,
  open_positions    integer default 0,
  version           text,
  updated_at        timestamptz not null default now(),
  unique(user_id)
);

-- Rename column to match JS camelCase expectations
-- (Supabase returns snake_case, JS code maps it — both work)

-- ── bot_commands ───────────────────────────────────────────
-- Frontend writes here. Backend reads + acks.
-- Commands: START | STOP | PAUSE | RESUME | UPDATE_SETTINGS
create table if not exists bot_commands (
  id          uuid primary key default uuid_generate_v4(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  command     text not null,       -- START | STOP | PAUSE | RESUME | UPDATE_SETTINGS
  payload     jsonb,               -- optional: { patienceMode, strategyToggles, sizingMode, ... }
  status      text not null default 'PENDING', -- PENDING | DONE
  created_at  timestamptz not null default now(),
  acked_at    timestamptz
);

-- ── engine_logs ────────────────────────────────────────────
-- Backend appends structured log entries. Frontend displays.
create table if not exists engine_logs (
  id          uuid primary key default uuid_generate_v4(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  level       text not null,   -- INFO | TRADE | WARN | ERROR
  message     text not null,
  data        jsonb,
  created_at  timestamptz not null default now()
);

-- ── market_snapshots ───────────────────────────────────────
-- One row per user+symbol. Updated every analysis cycle.
create table if not exists market_snapshots (
  id          uuid primary key default uuid_generate_v4(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  symbol      text not null default 'BTCUSDT',
  data        jsonb,
  updated_at  timestamptz not null default now(),
  unique(user_id, symbol)
);

-- ── signal_log ─────────────────────────────────────────────
-- All signals generated by the backend worker.
create table if not exists signal_log (
  id          uuid primary key default uuid_generate_v4(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  signal_id   text not null,
  data        jsonb,
  updated_at  timestamptz not null default now(),
  unique(signal_id)
);

-- ── Existing tables (from v1 setup — run if not done) ──────

create table if not exists settings (
  id          uuid primary key default uuid_generate_v4(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  key         text not null,
  value       jsonb,
  updated_at  timestamptz not null default now(),
  unique(user_id, key)
);

create table if not exists trades (
  id          uuid primary key default uuid_generate_v4(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  trade_id    text not null,
  data        jsonb,
  updated_at  timestamptz not null default now(),
  unique(trade_id)
);

create table if not exists notes (
  id          uuid primary key default uuid_generate_v4(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  trade_id    text not null,
  note        text,
  updated_at  timestamptz not null default now(),
  unique(user_id, trade_id)
);

-- ── Row Level Security ──────────────────────────────────────
alter table bot_status       enable row level security;
alter table bot_commands     enable row level security;
alter table engine_logs      enable row level security;
alter table market_snapshots enable row level security;
alter table signal_log       enable row level security;
alter table settings         enable row level security;
alter table trades           enable row level security;
alter table notes            enable row level security;

-- Drop and recreate policies safely
do $$ begin
  -- bot_status
  drop policy if exists "bot_status: own rows" on bot_status;
  create policy "bot_status: own rows" on bot_status
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

  -- bot_commands
  drop policy if exists "bot_commands: own rows" on bot_commands;
  create policy "bot_commands: own rows" on bot_commands
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

  -- engine_logs
  drop policy if exists "engine_logs: own rows" on engine_logs;
  create policy "engine_logs: own rows" on engine_logs
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

  -- market_snapshots
  drop policy if exists "market_snapshots: own rows" on market_snapshots;
  create policy "market_snapshots: own rows" on market_snapshots
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

  -- signal_log
  drop policy if exists "signal_log: own rows" on signal_log;
  create policy "signal_log: own rows" on signal_log
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

  -- settings
  drop policy if exists "settings: own rows" on settings;
  create policy "settings: own rows" on settings
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

  -- trades
  drop policy if exists "trades: own rows" on trades;
  create policy "trades: own rows" on trades
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

  -- notes
  drop policy if exists "notes: own rows" on notes;
  create policy "notes: own rows" on notes
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
end $$;

-- ── Backend service role bypass (for the worker) ───────────
-- The backend uses service key which bypasses RLS automatically.
-- No additional policy needed for the worker.

-- ── Indexes ─────────────────────────────────────────────────
create index if not exists idx_bot_commands_user_status on bot_commands(user_id, status);
create index if not exists idx_engine_logs_user         on engine_logs(user_id, created_at desc);
create index if not exists idx_signal_log_user          on signal_log(user_id);
create index if not exists idx_trades_user              on trades(user_id);
create index if not exists idx_settings_user            on settings(user_id);

-- ── Enable Realtime ──────────────────────────────────────────
-- Enable via: Supabase Dashboard → Database → Replication → Enable for these tables
alter publication supabase_realtime add table bot_status;
alter publication supabase_realtime add table bot_commands;
alter publication supabase_realtime add table engine_logs;
alter publication supabase_realtime add table market_snapshots;
alter publication supabase_realtime add table signal_log;
alter publication supabase_realtime add table trades;
alter publication supabase_realtime add table settings;
alter publication supabase_realtime add table notes;

-- ── Auto-cleanup old engine logs (keep 7 days) ──────────────
-- Optional: run this manually if logs table gets large
-- delete from engine_logs where created_at < now() - interval '7 days';

select 'Alpha Bot v2 schema setup complete ✓' as result;
